### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by alphapapa** [chameco/raven#1]
Hi,

This looks very interesting.  Some screenshots would be great.

BTW, would you consider changing the wording of this?

> used Helm heavily, but I disliked how bulky and unpredictable it was (timers, yuck). 

Helm may not be for everyone, but it's had thousands of hours of work put into it to support a wide variety of use cases, while working around Emacs' awkward innards, and it does so very well.  It would be nice if it didn't need to work the way it does, but it's not Thierry's fault that Emacs is the way it is.  Even in my comparatively simple projects that use Emacs timers and external async processes, I've come to appreciate what a mess it is to work with them.  I'm very thankful that he's done the work to make a powerful tool so the rest of us can remain blissfully ignorant of the problems it abstracts over.

Thanks.

**Comment by chameco** [comment]
Sure, I'll change that. I certainly don't want it to sound like I'm bashing Helm, or even passing this library off as a viable alternative. I love Helm, I've used it for years, and I thoroughly appreciate the work that's gone into it.

GIFs soon.

**Comment by chameco** [comment]
nil
